config/routes.rb
Sea::Application.routes.draw do
  get "about" => "about#index"
  get "syllabus/index"
  get "welcome/index"

  resources :videos

  resources :lessons

  resources :courses do
      resources :lessons
      resources :syllabus do
          get 'page/:page', :action => :index, :on => :collection
      end
  end

  root 'welcome#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
    has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :lesson
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
      l_id = params[:l] ? params[:l].to_i : 1
      @lessons = @course.lessons.page(params[:page]).per(20)
      @video = @course.lessons[l_id - 1].videos.first
  end

  # GET /courses/new
  def new
    @course = Course.new
    redirect_to action: 'index'
  end

  # GET /courses/1/edit
  def edit
    redirect_to @course
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :set_course

  # GET /lessons
  # GET /lessons.json
  def index
    if @course
        @lessons = @course.lessons
    else
        @lessons = Lesson.all
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    redirect_to action: 'index'
  end

  # GET /lessons/1/edit
  def edit
    redirect_to @lesson
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lesson }
      else
        format.html { render action: 'new' }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def set_course
      if params[:course_id]
        @course = Course.find(params[:course_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :description, :number, :course_id)
    end
end

app/controllers/syllabus_controller.rb
class SyllabusController < ApplicationController
  def index
    @course = Course.find(params[:course_id])
    @lessons = @course.lessons.page(params[:page]).per(20)
    respond_to do |format|
      format.html { render "courses/_outline", layout: nil }
      format.json { head :no_content }
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
    redirect_to action: 'index'
  end

  # GET /videos/1/edit
  def edit
    redirect_to @video
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :url, :number, :lesson_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/syllabus_helper.rb
module SyllabusHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="home-header" style="margin-top: 40px; margin-bottom: 40px;">
    <div class="row centered-text">
        <div class="small-9 small-push-3 columns">
            <h3 style="color: #006887;">知识，乐趣，分享</h3>
            <p class="subheader">与万门不期而遇</p>
        </div>
        <div class="small-3 small-pull-9 columns">
            <h2 style="color: #008cba;">万门大学</h2>
        </div>
    </div>
</div>
<div class="home-content">
    <div class="row">
        <div class="panel">
            <h4><span class="glyphicon glyphicon-hand-right"></span> 万门是什么</h4>
            <p>
            万门大学不仅是一所网络大学，它也是一种信仰，这种信仰来自于我们相信每个人内在的价值，相信大学之道的存在；它更是一次中国高等教育改革的践行——在符合时代特征和发展规律的基础上，对大学精神以及大学教育进行深入的思考和尝试。
            </p>
            <h4><span class="glyphicon glyphicon-hand-right"></span> 万门的理想</h4>
            <p>
            万门大学致力于成为网络时代变革大学教育的践行者。
            </p>
            <p>
            大学教育对于一个国家是至关重要的，它的使命是将一个国家相对优秀的人才进行培养，以使他们成为未来社会和国家发展的推动者和规划者。故而大学教育的成败将决定一个国家的未来。无需赘言，中国大学教育存在诸多问题，改革也已是老生常谈。而在今天这样一个时代，高等教育的改革离不开传统实体高校的努力，同样也离不开民间办学力量的参与和创新。
            </p>
            <p>
            万门大学正是在这样的时代背景下建立并逐渐成长起来的。万门大学不是一所传统意义上的大学，也无法取代实体大学，但我们致力于用自己的思考和专注，做我们应该做的事情，做我们可以做好的事情，对传统高校进行补充，同实体大学进行配合，共同参与到变革大学教育的进程中。
            </p>
            <h4><span class="glyphicon glyphicon-hand-right"></span> 万门的信仰</h4>
            <p>
            我们相信，每一个人的内在都拥有无限的潜能，在这一点上所有的人都是平等的，无论其出身、性别、学历、社会地位如何，他的内心都有潜能去理解和领悟世间的一切规律和智慧。万门大学将和万千青年人一起唤起自我改变的力量，打开自我内心深处的那扇大门，从而让智慧与美德的光芒照亮世界。
            </p>
            <p>
            我们相信，大学是要对某种精神进行传承的，这种价值和理念是要特别对历史和未来负责的，而不单单或者仅仅是对现在负责。万门大学以“独立之思考，求实之精神，人文之情怀”为立校精神，这种精神将在万门大学的每一个人、每一门课、每一项活动中得以体现，并将不断的传承给后来的每一位加入者，让它影响更多的人，让它一代代传承下去，坚持下去。
            </p>
            <p>
            我们相信，大学是要坚守其教育责任的。万门大学不是要做一个传播知识的百科全书，或是培养锻炼特定技能的培训机构，而是希望带给大家知识上的收获，学到那些足以影响他们一生的东西，掌握推动与支配自己的力量；坚持并全力与去培养一个完整的人，一个拥有独立思考、求实精神和人文情怀的人。
            </p>
            <p>
            我们相信，大学是需要创造一种氛围的，让学生认识到自我对于家庭、社会、国家、甚至整个人类的价值，并将这种认识上升为一种责任感和使命感。万门大学希望引导大家学会思考自己、思考世界，明确自己在世界中的位置，拥有“我想成为一个什么样的人”的视野，进而去追求富有意义的人生。
            </p>
        </div>
    </div>
</div>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/_outline.html.erb
<ul class="no-bullet">
    <% @lessons.each do |lesson| %>
        <li>
            <div class="clearfix">
                <a href="?l=<%= lesson.number %>">第 <%= lesson.number %> 集</a>
                <p class="subheader right"><%= lesson.title %></p>
            </div>
        </li>
    <% end %>
</ul>
<%= paginate @lessons, :window => 4, :remote => true, :outer_window => 2,
    :params  => {:controller => "syllabus",
                 :course_id => @course.id,
                 :action => "index",
                 :id => nil} %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="home-header" style="margin-top: 40px; margin-bottom: 40px;">
    <div class="row centered-text">
        <div class="small-9 small-push-3 columns">
            <h3 style="color: #006887;">知识，乐趣，分享</h3>
            <p class="subheader">与万门不期而遇</p>
        </div>
        <div class="small-3 small-pull-9 columns">
            <h2 style="color: #008cba;">万门大学</h2>
        </div>
    </div>
</div>

<div class="row">
    <h3>课程列表</h3>
</div>

<div class="home-content">
    <div class="row">
        <div class="panel">
            <table>
                <thead>
                    <tr>
                        <th width="240">课程名</th>
                        <th width="240">描述</th>
                        <th width="240"></th>
                    </tr>
                </thead>
                <tbody>
                <% @courses.each do |course| %>
                    <tr>
                    <td><%= course.title %></td>
                    <td><%= course.description %></td>
                    <td><%= link_to '查看', course %></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/outline.html.erb
<%= render "outline" %>

app/views/courses/show.html.erb
<% if notice %>
<div class="row">
    <div data-alert class="alert-box info">
      <!-- Your content goes here -->
      <p id="notice">
        <%= notice %>
        <a href="#" class="close">&times;</a>
      </p>
    </div>
</div>
<% end %>

<div>
    <div class="row" style="margin-top: 20px; margin-bottom: 20px;">
        <div class="columns">
            <h2><%= @course.title %></h2>
        </div>
    </div>
</div>

<div class="course-content" style="background: #efefef;">
    <div class="row" style="padding-top: 30px;">
        <div class="large-9 columns">
            <div class="course-video">
                <% if @video %>
                <div class="flex-video">
                    <iframe width="420" height="315" src="<%= @video.url %>" frameborder="0" allowfullscreen></iframe>
                </div>
                <% else %>
                <p>暂无视频</p>
                <% end %>
            </div>
        </div>
        <div class="large-3 columns" style="background: white;">
            <div class="course-outline" style="padding-top: 15px;">
                <%= render "outline" %>
            </div>
        </div>
    </div>
</div>

<div class="course-detail" style="background: #085a78;">
    <div class="row" style="padding-top: 20px; padding-bottom: 20px; color: white;">
        <div class="columns">
            <p>
            <strong>课程名:</strong>
            <%= @course.title %>
            </p>

            <p>
            <strong>课程描述:</strong>
            <%= @course.description %>
            </p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "万门大学" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="contain-to-grid fixed">
        <nav class="top-bar" data-topbar>
            <section class="top-bar-section">
                <!-- Right Nav Section -->
                <ul class="right">
                    <li><a href="/courses">课程列表</a></li>
                </ul>

                <!-- Left Nav Section -->
                <ul class="left">
                    <li><a href="/">万门大学</a></li>
                </ul>
            </section>
        </nav>
    </div>

    <%= yield %>

    <div class="footer">
        <div class="row">
            <div class="medium-4 medium-4 push-8 columns">
            </div>
            <div class="medium-8 medium-8 pull-4 columns">
                <ul class="zurb-links">
                    <li><a href="/about">关于万门</a></li>
                </ul>
                <p class="copyright">© 2012-2013 wanmen.org, All rights reserved.</p>
            </div>
        </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="row">
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>
</div>

app/views/lessons/index.html.erb
<div class="row">
<h1>Listing lessons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Number</th>
      <th>Course</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.description %></td>
        <td><%= lesson.number %></td>
        <td><%= lesson.course %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>
</div>

app/views/lessons/new.html.erb
<div class="row">
<h1>New lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>
</div>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lesson.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @lesson.number %>
</p>

<p>
  <strong>Course:</strong>
  <%= @lesson.course %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>

app/views/syllabus/index.html.erb
<h1>Syllabus#index</h1>
<p>Find me in app/views/syllabus/index.html.erb</p>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :lesson_id %><br>
    <%= f.text_field :lesson_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<div class="row">
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Url</th>
      <th>Number</th>
      <th>Lesson</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= video.url %></td>
        <td><%= video.number %></td>
        <td><%= video.lesson %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>
</div>

app/views/videos/new.html.erb
<div class="row">
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @video.url %>
</p>

<p>
  <strong>Number:</strong>
  <%= @video.number %>
</p>

<p>
  <strong>Lesson:</strong>
  <%= @video.lesson %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>

app/views/welcome/index.html.erb
<div class="home-header" style="margin-top: 40px; margin-bottom: 40px;">
    <div class="row centered-text">
        <div class="small-9 small-push-3 columns">
            <h3 style="color: #006887;">知识，乐趣，分享</h3>
            <p class="subheader">与万门不期而遇</p>
        </div>
        <div class="small-3 small-pull-9 columns">
            <h2 style="color: #008cba;">万门大学</h2>
        </div>
    </div>
</div>

<div class="home-content">
    <div class="row">
        <div class="panel">
            <h4>物理</h4>
            <a class="th" href="/courses/3">
                <img src="<%= asset_path("3.jpeg") %>">
                <span class="label">广义相对论</span>
            </a>
            <a class="th" href="/courses/4">
                <img src="<%= asset_path("4.jpeg") %>">
                <span class="label">理论物理一月特训班</span>
            </a>
            <a class="th" href="/courses/5">
                <img src="<%= asset_path("5.jpeg") %>">
                <span class="label">热力学与统计物理</span>
            </a>
            <a class="th" href="/courses/6">
                <img src="<%= asset_path("6.jpeg") %>">
                <span class="label">理论物理科学家班</span>
            </a>
            <a class="th" href="/courses/7">
                <img src="<%= asset_path("7.jpeg") %>">
                <span class="label">量子力学</span>
            </a>
        </div>
        <div class="panel">
            <h4>数学</h4>
            <a class="th" href="/courses/8">
                <img src="<%= asset_path("8.jpeg") %>">
                <span class="label">线性代数</span>
            </a>
            <a class="th" href="/courses/9">
                <img src="<%= asset_path("9.jpeg") %>">
                <span class="label">高等数学</span>
            </a>
            <a class="th" href="/courses/10">
                <img src="<%= asset_path("10.jpeg") %>">
                <span class="label">数学物理方法</span>
            </a>
        </div>
        <div class="panel">
            <h4>计算机</h4>
            <a class="th" href="/courses/1">
                <img src="<%= asset_path("1.jpeg") %>">
                <span class="label">有限状态自动机</span>
            </a>
        </div>
    </div>
</div>